import asyncio
import logging

from app.core.config import settings
from app.core.database import SessionLocal
from app.services.backup import run_db_backup
from app.services.quality import generate_quality_metrics

logger = logging.getLogger(__name__)


async def quality_metrics_scheduler() -> None:
    interval_seconds = max(settings.quality_metrics_interval_hours, 1) * 3600
    while True:
        db = SessionLocal()
        try:
            generate_quality_metrics(db)
            logger.info("Quality metrics successfully generated by scheduler")
        except Exception as e:
            logger.error(f"Quality Metrics Scheduler Error: {e}")
        finally:
            db.close()
        await asyncio.sleep(interval_seconds)


async def daily_backup_scheduler() -> None:
    interval_seconds = 24 * 3600
    while True:
        try:
            run_db_backup()
            logger.info("Daily database backup successfully completed by scheduler")
        except Exception as e:
            logger.error(f"Daily Backup Scheduler Error: {e}")
        await asyncio.sleep(interval_seconds)
